In [1]:
import numpy as np

In [ ]:
array = np.array([[10,20,30],
                  [40,50,60],
                  [70,80,90]])
print(array.ndim)#ndim retorna o numero de dimensões, aqui no caso são duas, sendo elas linhas e colunas
print(array.shape)#aqui é o elemento existente de cada dimensão, sendo 3 linhas e 3 colunas
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
#buscar o elemento na linha 1 e na coluna 2
elemento = array[2,2]
elemento
#coluna 0,1 e 2 e linhas também, 60=linha 1 e coluna 2. 90 é linha 2 e coluna 2

np.int64(90)

In [8]:
#pegar dados da primeira linha
linha_0=array[0]
linha_0

array([10, 20, 30])

In [10]:
#acessando a coluna 1:
coluna_1= array[:,1]
coluna_1

array([20, 50, 80])

In [11]:
#fatiamento para obter um subarray
#linha p a 1 e coluna 1 e 2
subarray = array [0:2,1:3]
subarray

array([[20, 30],
       [50, 60]])

In [13]:
mascara = array >50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [14]:
elementos_maiores_que_50 = array [mascara]
elementos_maiores_que_50

array([60, 70, 80, 90])

In [15]:
#modificando elemento na linha 1, coluna 1
array[1,1]=100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])