In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [4]:
#1-adição
soma = np.add(array,10)
soma

array([11, 12, 13, 14, 15])

In [6]:
#subtração
subtracao = np.subtract(array, 1)
subtracao

array([0, 1, 2, 3, 4])

In [7]:
#multiplicação
mult = np.multiply(array, 2)
mult

array([ 2,  4,  6,  8, 10])

In [8]:
#divisao
divisao = np.divide(array, 2)
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [9]:
#função trigonometrica
seno = np.sin(array)
seno

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [10]:
cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [12]:
media = np.mean(array)
media

np.float64(3.0)

In [13]:
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.4142135623730951)

In [ ]:
maiorq = array > 3
maiorq

array([False, False,  True,  True,  True])

In [16]:
#combinando funçoes
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])